version: "3.9"
services:
  job:
    restart: always
    image: zonneconnect:latest
    build:
        context: .
        args:
            UUID: ${UUID:-1000}
            GID: ${GID:-1000}
    environment:
      UUID: ${UUID:-1000}
      GID: ${GID:-1000}
    user: "${UUID}:${GID}"
    volumes:
        - ./data:/app/data 
    env_file:
        - ./.env
